### PR TITLE
Update node-glfw to go from nan 0.8 to 1.6 to support node12/iojs

### PR DESCRIPTION
**Pull request by lmeyerov**
AFAICT, still works with node 10.26  as well. Did not test on node 11.

### CODE REVIEW

**Comment by jhludwig** [comment]
is this request going to be merged anytime soon?  i am interested in trying it out...

**Comment by ronkorving** [comment]
:+1: can we have some progress on NAN integration? :)

**Comment by lmeyerov** [comment]
@mikeseven Do we need this for node-opencl? (We'll be trying to merge into mainline of that next week, not sure if this part is still relevant.)

**Comment by mikeseven** [comment]
Node-opencl doesn't use any graphical library such Opengl and thus no
windowing system, so no dependency on glfw and no dependency on node-webgl.

Node-opencl is tested on node 0.12 and iojs.

I plan on deprecate node-webcl for node-opencl this month. If you use
OpenCL, use node-opencl. It supports up to OpenCL 2.0 for now, while webcl
is only 1.1.

--mike

**Pull request closed without merging**
